import { readdirSync, readFileSync } from "node:fs";
import { dirname, extname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const dir = dirname(fileURLToPath(import.meta.url));
const srcRoot = join(dir, "..", "..");
const rootLayoutSource = readFileSync(join(srcRoot, "app", "layout.tsx"), "utf8");
const docsServerLayoutSource = readFileSync(join(srcRoot, "app", "(public)", "docs", "layout.tsx"), "utf8");
const docsLayoutSource = readFileSync(join(srcRoot, "app", "(public)", "docs", "layout.client.tsx"), "utf8");
const globalCssSource = readFileSync(join(srcRoot, "app", "global.css"), "utf8");
const docsCssSource = readFileSync(join(srcRoot, "app", "(public)", "docs", "docs.css"), "utf8");
const docsThemeCssSource = readFileSync(join(srcRoot, "app", "(public)", "docs", "fumadocs-theme.css"), "utf8");
const scopedDocsCssSource = readFileSync(join(srcRoot, "app", "(public)", "docs", "fumadocs-scoped.css"), "utf8");

function listSourceFiles(directory: string): string[] {
  return readdirSync(directory, { recursive: true, encoding: "utf8" })
    .filter((entry) => [".ts", ".tsx"].includes(extname(entry)))
    .map((entry) => join(directory, entry));
}

describe("Fumadocs UI boundary", () => {
  it("keeps fumadocs-ui imports inside the docs route and docs feature", () => {
    const violations = listSourceFiles(srcRoot)
      .filter((file) => /from ["']fumadocs-ui/.test(readFileSync(file, "utf8")))
      .map((file) => relative(srcRoot, file))
      .filter((file) => !file.startsWith("app/(public)/docs/") && !file.startsWith("features/docs/"));

    expect(violations).toEqual([]);
  });

  it("initializes static search only in the docs provider", () => {
    expect(rootLayoutSource).not.toMatch(/fumadocs|search=\{/);
    // Above ClientLayout, which subscribes to usePathname() — nesting it there
    // would rebuild the search context on every docs navigation.
    expect(docsServerLayoutSource).toMatch(/RootProvider/);
    expect(docsLayoutSource).not.toMatch(/RootProvider/);
    // Matched loosely so reformatting the prop does not fail a passing runtime.
    expect(docsServerLayoutSource).toMatch(/type: "static"/);
  });

  it("keeps Fumadocs CSS out of the global stylesheet", () => {
    expect(globalCssSource).not.toMatch(/fumadocs-ui/);
    expect(globalCssSource).toMatch(/@custom-variant dark/);
  });

  it("loads Fumadocs CSS only from the docs entry stylesheet", () => {
    expect(docsCssSource).toMatch(/@import "\.\/fumadocs-scoped\.css"/);
    expect(docsCssSource).toMatch(/@import "\.\/fumadocs-theme\.css"/);
    // The docs entry composes; it must not start a second Tailwind build.
    expect(docsCssSource).not.toMatch(/@import "tailwindcss"|@reference/);
  });

  it("scopes Fumadocs CSS without adding specificity", () => {
    // A bare `html:has(#nd-docs-layout)` prefix adds specificity to every Fumadocs rule,
    // which flips cascade winners against project CSS: Fumadocs' `.dark` palette
    // would outrank fumadocs-theme.css, and its `--radius-*` would outrank :root.
    // `:where()` keeps every upstream specificity relationship intact.
    expect(scopedDocsCssSource).toMatch(/^\/\* Generated by scripts\/generate-fumadocs-scoped-css\.mjs/);
    expect(scopedDocsCssSource).toMatch(/:where\(html:has\(#nd-docs-layout\)\)/);
    expect(scopedDocsCssSource.replaceAll(":where(html:has(#nd-docs-layout))", "")).not.toMatch(/html:has\(#nd-docs-layout\)/);
    // Keyframe stops are positions, not selectors, so they must stay unscoped.
    expect(scopedDocsCssSource).not.toMatch(/:where\(html:has\(#nd-docs-layout\)\)\s+(?:from|to|\d+%)/);
    // Tailwind's `layout:` variant uses an ancestor selector with `:has(&)`.
    // Scope that ancestor, not the utility substituted into `&`, or all docs
    // layout widths remain at their zero-value mobile defaults.
    expect(scopedDocsCssSource).toContain(":where(html:has(#nd-docs-layout)) #nd-docs-layout:has(&)");
    expect(scopedDocsCssSource).not.toContain(":where(html:has(#nd-docs-layout)) .md\\:layout\\:");
    // The rewriter only visits rules, so an at-rule-scoped sheet would slip past it.
    expect(scopedDocsCssSource).not.toMatch(/@scope/);
  });

  it("bridges Fumadocs tokens to the project palette", () => {
    expect(docsThemeCssSource).toMatch(/html:has\(#nd-docs-layout\)/);
    // Mode-agnostic by design: `--background` already flips under `.dark`, and
    // the bridge outranks the scoped sheet's dark block on specificity.
    expect(docsThemeCssSource).toMatch(/--color-fd-background:\s*var\(--background\)/);
  });

  it("derives the docs CSS boundary from the Fumadocs layout root", () => {
    expect(docsLayoutSource).toMatch(/DocsLayout/);
    expect(docsServerLayoutSource).not.toMatch(/DocsRouteMarker|<script/);
    expect(scopedDocsCssSource).toMatch(/html:has\(#nd-docs-layout\)/);
  });
});
